- name: Deploy Calico configuration
  ansible.builtin.template:
    src: calico-config.j2
    dest: /var/lib/rancher/rke2/server/manifests/calico-config.yaml
    owner: root
    group: root
    mode: "0644"

- name: Render CalicoNodeStatus manifest template
  ansible.builtin.template:
    src: calico-node-status.yaml.j2
    dest: /var/lib/rancher/rke2/server/manifests/calico-node-status.yaml
    owner: root
    group: root
    mode: "0644"
