# Deploy metal IP Pool to Server 1
- name: Copy ArgoCD manifest template
  ansible.builtin.template:
    src: argocd.yaml.j2
    dest: /home/{{ ansible_user }}/argocd.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  when: inventory_hostname == groups['servers'][0] and deploy_argocd == true

- name: Apply ArgoCD manifest template
  ansible.builtin.command:
    cmd: kubectl apply -f /home/{{ ansible_user }}/argocd.yaml
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0] and deploy_argocd == true
