- name: Check all nodes are ready
  ansible.builtin.command:
    cmd: kubectl get nodes | grep -w "NotReady" | wc -l
  register: cmd_output
  until: cmd_output.stdout | int == 0
  retries: 120
  delay: 10
  become: yes
  become_user: "{{ ansible_user }}"
  ignore_errors: true

- name: Apply Argocd
  ansible.builtin.import_tasks:
    argocd.yaml
  when: deploy_argocd == true
