- name: Apply Tigera Operator manifest
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]

- name: Render CalicoConfig manifest template

  ansible.builtin.template:
    src: calico-config.yaml.j2
    dest: calico-config.yaml
  when: inventory_hostname == groups['servers'][0]

- name: Apply CalicoConfig manifest
  ansible.builtin.command:
    cmd: kubectl apply -f calico-config.yaml
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]

- name: Render CalicoNodeStatus manifest template
  ansible.builtin.template:
    src: calico-node-status.yaml.j2
    dest: calico-node-status.yaml
  when: inventory_hostname == groups['servers'][0]

- name: Apply CalicoNodeStatus manifest
  ansible.builtin.command:
    cmd: kubectl apply -f calico-node-status.yaml
  become_user: "{{ ansible_user }}"
  changed_when: true
  when: inventory_hostname == groups['servers'][0]

- name: Create calicoctl directory
  ansible.builtin.file:
    path: /etc/calico
    state: directory
    mode: '0755'

- name: Apply calicoctl config
  ansible.builtin.template:
    src: calicoctl.cfg.j2
    dest: /etc/calico/calicoctl.cfg
  become: true

- name: Download calicoctl
  get_url:
    url: https://github.com/projectcalico/calico/releases/download/v3.28.0/calicoctl-linux-amd64
    dest: /usr/local/bin/calicoctl
    mode: '0755'

- name: Ensure calicoctl is executable
  file:
    path: /usr/local/bin/calicoctl
    mode: '0755'
    state: file
