# Keep checking the cluster API until it's functioning (deployed)
- name: Wait for cluster API to be ready (can take 5-10 mins depending on internet/hardware)
  ansible.builtin.command:
    cmd: "kubectl get nodes"
  register: kubectl_output
  until: "'connection refused' not in kubectl_output.stderr"
  retries: "{{ max_retries }}"
  delay: "{{ delay }}"
  changed_when: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['servers'][0]

- name: Check if all nodes are ready
  shell: kubectl get nodes --no-headers | awk '{print $2}' | grep -v '\<Ready\>' | wc -l
  register: nodes_not_ready_count
  until: (nodes_not_ready_count.stdout | int == 0) and "'connection refused' not in nodes_not_ready_count.stderr"
  retries: "{{ max_retries }}"
  delay: "{{ delay }}"
  become_user: "{{ ansible_user }}"
  changed_when: false
  ignore_errors: true
  failed_when: false

- name: Debug nodes_not_ready_count
  debug:
    var: nodes_not_ready_count

- name: Check if all essential pods are running
  shell: |
    kubectl get pods -n kube-system --no-headers | awk '{print $3}' | grep -v 'Running' | grep -v 'Completed' | wc -l
  loop: "{{ essential_namespaces }}"
  register: pods_not_running_count
  until: (pods_not_running_count.stdout | int == 0)  and "'connection refused' not in pods_not_running_count.stderr"
  retries: "{{ max_retries }}"
  delay: "{{ delay }}"
  become_user: "{{ ansible_user }}"
  changed_when: false
  ignore_errors: true
  failed_when: false

- name: Debug pods_not_running_count
  debug:
    var: pods_not_running_count

- name: Set loop success if all nodes and pods are ready
  set_fact:
    loop_success: true
  when: nodes_not_ready_count.stdout | int == 0 and pods_not_running_count.results | map(attribute='stdout') | map('int') | sum == 0

- name: Reboot the node if nodes or pods are not ready
  block:
  - name: Increment loop counter
    set_fact:
      loop_counter: "{{ loop_counter | int + 1 }}"

  - name: Reboot the node
    reboot:
      reboot_timeout: 300
    when: loop_counter < max_loops

  - name: Wait before retrying
    pause:
      minutes: 2
  when: not loop_success
