# Keep checking the cluster API until it's functioning (deployed)
- name: Wait for cluster API to be ready (can take 5-10 mins depending on internet/hardware)
  ansible.builtin.command:
    cmd: "kubectl get nodes"
  register: kubectl_output
  until: "'connection refused' not in kubectl_output.stderr"
  retries: 120
  delay: 10
  changed_when: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['servers'][0]

- name: Ensure nodes and essential pods are ready (main loop)
  block:
  - name: Check if all nodes are ready
    shell: kubectl get nodes --no-headers | awk '{print $2}' | grep -v 'Ready' | wc -l
    register: nodes_not_ready_count
    until: nodes_not_ready_count.stdout | int == 0
    retries: "{{ max_retries }}"
    delay: "{{ delay }}"
    changed_when: false
    become_user: "{{ ansible_user }}"

  - name: Debug nodes_not_ready_count
    debug:
      var: nodes_not_ready_count

  - name: Check if all essential pods are running
    shell: |
      kubectl get pods -n {{ item }} --no-headers | awk '{print $3}' | grep -v 'Running' | wc -l
    loop: "{{ essential_namespaces }}"
    register: pods_not_running_count
    until: pods_not_running_count | map(attribute='stdout') | map('int') | sum == 0
    retries: "{{ max_retries }}"
    delay: "{{ delay }}"
    changed_when: false
    become_user: "{{ ansible_user }}"

  - name: Debug pods_not_running_count
    debug:
      var: pods_not_running_count

  - name: Check if any essential pods are not running
    fail:
      msg: "Not all essential pods are in 'Running' state."
    when: pods_not_running_count | map(attribute='stdout') | map('int') | sum != 0

  rescue:

  - name: Reboot nodes that are not ready
    shell: |
      for node in $(kubectl get nodes --no-headers | awk '{print $1}'); do
        if ! kubectl get node $node -o json | jq -e '.status.conditions[] | select(.type=="Ready" and .status=="True")'; then
          node_ip=$(kubectl get node $node -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}')
          ssh -o StrictHostKeyChecking=no root@$node_ip "reboot"
        fi
      done
    register: reboot_result
    become_user: "{{ ansible_user }}"

  - name: Wait before retrying
    pause:
      minutes: 1

  - include_task: cluster_status_check.yml


- name: Add new servers or agents
  debug:
    msg: "Cluster is ready. Proceeding to add new servers or agents."

