# Create directory to deploy kube-vip manifest
- name: Create directory for Kube VIP Manifest
  ansible.builtin.file:
    path: "/var/lib/rancher/rke2/server/manifests"
    state: directory
    mode: "0755"
  when: inventory_hostname in groups['servers']

- name: Fetch GitHub tags page
  ansible.builtin.uri:
    url: "https://github.com/kube-vip/kube-vip/tags"
    return_content: yes
  register: kube_vip_tags_page

- name: Set latest kube-vip version
  ansible.builtin.set_fact:
    kube_vip_version: "{{ kube_vip_tags_page.content | regex_search('href=\"/[^\"]+/releases/tag/([^\"]+)', '\\1') | first }}"
  when: kube_vip_version == "latest"

# Copy kube-vip to server 1 manifest folder for auto deployment at bootstrap
- name: Deploy Kube VIP Configuration
  ansible.builtin.template:
    src: kube-vip-config.j2
    dest: /var/lib/rancher/rke2/server/manifests/kube-vip.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]

- name: Download KubeVip config file
  ansible.builtin.get_url:
    url: https://kube-vip.io/manifests/rbac.yaml
    dest: /var/lib/rancher/rke2/server/manifests/kube-rbac.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]
  
- name: Download KubeVip config file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml
    dest: /var/lib/rancher/rke2/server/manifests/kube-vip-controller.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]
