# Create a directory to download RKE2 binary to
- name: Create directory for RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}"
    state: directory
    mode: "0755"

- name: Set latest release version
  ansible.builtin.set_fact:
    rke2_url: "https://github.com/rancher/rke2/releases/latest/download/"
  when: rke2_version == "latest"

- name: Set release version
  ansible.builtin.set_fact:
    rke2_url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version }}"
  when: rke2_version != "latest"

- name: Determine system architectures
  set_fact:
    architecture_type: >-
      {% if ansible_architecture == 'x86_64' %}amd64{% elif ansible_architecture == 'aarch64' %}arm64{% else %}{{ ansible_architecture }}{% endif %}

# Download the RKE2 binary
- name: Download RKE2 binary
  ansible.builtin.get_url:
    url: "{{ rke2_binary_url }}"
    dest: "{{ rke2_install_dir }}/rke2"
    mode: "0755"

# Set permissions on the RKE2 binary
- name: Set executable permissions on the RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}/rke2"
    mode: "0755"
    state: file
