- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
  tags: sysctl

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  tags: sysctl

- name: Install network manager
  ansible.builtin.package:
    name: network-manager
    state: present

- name: Copy my_file.txt to remote server
  copy:
    src: calico-network-manager.conf
    dest: /etc/NetworkManager/conf.d/calico.conf
