- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
  tags: sysctl

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  tags: sysctl

- name: check packages
  package_facts:
    manager: auto

- name: Copy network manager
  copy:
    src: calico-network-manager.conf
    dest: /etc/NetworkManager/conf.d/calico.conf
  when: "'NetworkManager' in ansible_facts.packages"
